name: basanal_mad3_final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  form_field_validator: ^1.1.0
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  location: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
