// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEukbXRvgux50LIwfMiwFArP50q3bt55U',
    appId: '1:282263287375:web:4e06fdbcc91cbac02fdc3a',
    messagingSenderId: '282263287375',
    projectId: 'basanal-map-journal',
    authDomain: 'basanal-map-journal.firebaseapp.com',
    storageBucket: 'basanal-map-journal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfNNVuh-d8UaNIPklph2uC4-ISOhF3lNI',
    appId: '1:282263287375:android:ea2e242295c152242fdc3a',
    messagingSenderId: '282263287375',
    projectId: 'basanal-map-journal',
    storageBucket: 'basanal-map-journal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVdSwVplR7gWjPYAf1IhpjjLjZWARa34o',
    appId: '1:282263287375:ios:4cec3c8c199aee342fdc3a',
    messagingSenderId: '282263287375',
    projectId: 'basanal-map-journal',
    storageBucket: 'basanal-map-journal.appspot.com',
    iosBundleId: 'com.example.basanalMad3FinalProject',
  );
}
